---
version: "2"
checks:
  file-lines:
    config:
      threshold: 1000
  method-count:
    config:
      threshold: 50
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-23-0
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    # dump_ast and debug are optional for debugging to show the parsing tree
    config:
      # dump_ast: true
      # debug: true
      languages:
        javascript:
          # Filter for sidebar.js to prevent duplication call by the following pattern
          # Reads like this: "An ExpressionStatement node, with a expression node and an
          # AssignmentExpression node with any value, that contains a left MemberExpression node
          # with an object and any Identifier and a property with any Identifier plus a right
          # MemberExpression node with an object and any Identifier and a property with any Identifier
          filters:
          - "(ExpressionStatement (expression (AssignmentExpression _ (left(MemberExpression\
          (object (Identifier _))(property (Identifier _))false))(right(MemberExpression(object\
          (Identifier _))(property (Identifier _))false)))))"

          # Filter parsing tree explicitly for the generate_fasta function inside alignment_exporter.js
          # to prevent duplication call
          - "(ExpressionStatement(expression(AssignmentExpression _(left(Identifier _))(right\
          (BinaryExpression(left(BinaryExpression(left(BinaryExpression(left(BinaryExpression(left(BinaryExpression\
          (left(BinaryExpression(left(BinaryExpression(left(BinaryExpression(left(BinaryExpression(left(BinaryExpression(left\
          (StringLiteral _ _ _))_(right(MemberExpression(object (Identifier _))(property (Identifier _))false))))_(right\
          (StringLiteral _ _ _))))_(right(MemberExpression(object (Identifier _))(property (Identifier _))false))))_(right\
          (StringLiteral _ _ _))))_(right(MemberExpression(object (Identifier _))(property (Identifier _))false))))_(right\
          (StringLiteral _ _ _))))_(right(MemberExpression(object (Identifier _))(property (Identifier _))false))))_\
          (right, (StringLiteral _ _ _))))_(right(CallExpression(callee (Identifier _))(arguments(MemberExpression\
          (object (Identifier _))(property (Identifier _))false))))))_(right (StringLiteral _ _ _)))))))"

          # 45 is default from codeclimate as long as there is no explicit reason to change, we should keep it
          mass_threshold: 45
        ruby:
          # default from codeclimate
          mass_threshold: 25
exclude_patterns:
- public/css/sequenceserver.min.css
- public/sequenceserver-*.min.js
- public/js/sequence.js
- public/js/kablammo/*
- public/vendor/**/*
- node_modules/**/*
- public/shims/**/*
- public/vendor/*
- spec/**/*
- coverage/
