---
version: "2"
checks:
  file-lines:
    config:
      threshold: 1000
  method-count:
    config:
      threshold: 50
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-23-0
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    # exclude_patterns:
    # - public/js/sidebar.js
    config:
      # dump_ast: true
      # debug: true
      languages:
        javascript:
          # Filter for sidebar.js to prevent duplication call by the following pattern
          # Reads like this: "Any BlockStatement node, with a body and an Expression
          # Statement node with anything in it, with an AssignmentExpression node with any
          #  value etc...
          filters:
          - "(BlockStatement(_(ExpressionStatement(_(AssignmentExpression _(_(MemberExpression\
          (_(_ _))(_(_ _))_))(_(MemberExpression(_(_ _))(_(_ _))_)))))(ExpressionStatement\
          (_(AssignmentExpression _(_(MemberExpression(_ (_ _)) (_ (_ _)) _))(_(_ (_ (_ _))\
          (_ (_ _))_)))))(ExpressionStatement(_(CallExpression(_(MemberExpression(_ (_ _))\
          (_ (_ _))_))(_ (_ _))))))(_))"
          mass_threshold: 45
        ruby:
          mass_threshold: 25
exclude_patterns:
- public/css/sequenceserver.min.css
- public/sequenceserver-*.min.js
- public/js/sequence.js
- public/js/kablammo/*
- public/vendor/**/*
- node_modules/**/*
- public/shims/**/*
- public/vendor/*
- spec/**/*
- coverage/
